name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
      - name: Scala Steward Github Action
        uses: scala-steward-org/scala-steward-action@v2.29.0
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Test
        run: sbt clean test scalafmtCheckAll
